name = "Dartis-Craft - SGCraft 2.0.6 - AIO Base Modpack"
author = "Dartis-Craft"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f7e5c0ca00382e4a629454856cb41ae4fb0059bdea2da84e23c4b4489be8d0db"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
