name = "Dartis-Craft - SGCraft 2.0.6 - AIO Base Modpack"
author = "Dartis-Craft"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ebb50c34fb94750d4350ab03e601ac074d3a5652f023a5c1c69781e189dd4a29"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
