name = "Dartis-Craft - SGCraft 2.0.6 - AIO Base Modpack"
author = "Dartis-Craft"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "26c4c14e19118b50ca430552228c4457c411e0a3dd615fd314b6344f33307b59"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
