name = "Dartis-Craft - SGCraft 2.0.6 - AIO Base Modpack"
author = "Dartis-Craft"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9d24af89b032507e080868be8e3f1831adcdc1b642f9cb7a9b09323b035e662e"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
