name = "Dartis-Craft - SGCraft 2.0.6 - AIO Base Modpack"
author = "Dartis-Craft"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a5bdd71a50bdaef21613d5f487e8be6c5ceb4a106ad97a33bc1d02dd1c813598"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
