name = "Dartis-Craft - SGCraft 2.0.6 - AIO Base Modpack"
author = "Dartis-Craft"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f0e00f116b07950b93362b1933ec4db9d5ec0fdb2e505bf0add3d3ee7f5da755"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
