name = "Dartis-Craft - SGCraft 2.0.6 - AIO Base Modpack"
author = "Dartis-Craft"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3e04a757655141945564b1ecdefe7a533d972b0476fbfee268a4df8e3c201eea"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
